plugins/utils.c
Remove unused variable.
Signed-off-by: Sebastian Herbszt <herbszt@gmx.de>
=> utils: remove unused variable

plugins/sslutils.c
=> sslutils: remove superfluous parenthesis

plugins/check_dns.c
Remove code dead since commit 4efa917.
=> check_dns: remove dead code

plugins/check_disk.c
=> check_disk: remove unused variables

plugins/negate.c
=> negate: remove unused variables

plugins/check_disk.c
Reverts monitoring-plugins/monitoring-plugins#1436
=> Revert "check_disk - show all disks if state is ok and option error only is used"

plugins-root/check_icmp.c, plugins/check_fping.c, plugins/check_http.c, plugins/check_ide_smart.c, plugins/check_ldap.c, plugins/check_ntp.c, plugins/check_ntp_peer.c, plugins/check_pgsql.c, plugins/check_radius.c, plugins/check_real.c, plugins/check_smtp.c, po/de.po, po/fr.po, po/monitoring-plugins.pot
=> Spelling fixes suggested by lintian

plugins/check_apt.c
=> check_apt: Add -l/--list option to print packages

plugins/check_curl.c, plugins/tests/check_curl.t
Hope that's better. Sorry, still learning (and forgetting in between).
=> Modified virtual host and port behaviour to match check_http.

.gitignore
Small PR but sending along for the sake of completeness!
=> Added a compiled plugin script that was missing from gitignore

plugins/check_cluster.c
This commit adds validation on the -d argument to ensure that valid Nagios status codes are are supplied (i.e 0,1,2,3).
=> check_cluster.c: Added data argument validation.

plugins/check_disk.c
Hi,
#1567 added support for including inode usage in perfdata (which is awesome). This small change adds the missing inline documentation.
Thanks,
Christopher
=> include -P switch in help

doc/developer-guidelines.sgml
"first" + "second to last" is every line right?
=> simplify documentation

plugins/check_tcp.c
=> check_tcp: add --sni

configure.ac
better use "ping -4" instead of "ping" if supported
=> fix for issue #1550

plugins/check_dns.c
=> check_dns: split multiple IP addresses passed in one -a argument

plugins/check_mysql_query.c
generated a PR from the provided patch
=> - fix for issue #1562

plugins/check_curl.c
Backport from check_http (regex size, clarified dual usage, show_body).
=> Feature check curl

plugins/check_disk.c
This patch was shared by Klaus Ethgen (@mowgli) at  https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800345#29
(Closes #1357)
=> check_disk: Fixing the stuff that is broken on btrfs

.github/prepare_debian.sh
I think, this might be the reason for the test problem in #1623
=> Use netcat-openbsd for debian explicitely

plugins/check_ups.c
Respect the size of the buffer. This fixes #1030
=> Fix possible overflow in check_ups

plugins-scripts/check_log.sh
Some cleanup stuff and shellcheck corrections.
Also:
* adds `-a|--all` option to print all matching lines,
* add  `-p|--perl-regex` option to use grep with perl style regex
* add  `-e|--extended-regex` option to use grep with extended regex style
=> Modernize check log

plugins/check_game.c
=> Update Url to qstat

plugins/check_ping.c
patch originated from pld-linux
https://github.com/pld-linux/monitoring-plugins/commits/auto/th/monitoring-plugins-2.1.2-1/nagios-plugins-ping.patch
=> [check_ping] understang ping6 output from iputils package

plugins-scripts/check_mailq.pl
=> Check mailq domain specific warnings

plugins/check_disk.c
…g in check_disk.
Should update/replace #1326
=> Trivial printf fix and a little bit of code style

plugins-root/check_icmp.c, plugins-root/t/check_icmp.t
- delay set_source_ip() until address_family is detected
- add a test to check '-s'
fix for  #1734
=> delay set_source_ip() until address_family is detected

plugins/check_curl.c, plugins/check_http.c
=> Enhancement --continue-after-certificate (backport from nagios-plugins)

plugins/check_by_ssh.c
This causes a 255 exit value from ssh(1), which indicates a connection failure,
to return UNKNOWN instead of CRITICAL; similar to check_nrpe's "-u" flag.
=> check_by_ssh: Add "-U" flag (#1123).

plugins/t/check_curl.t, plugins/t/check_http.t
=> Remove check_http and check_curl test which are somehow always failing

plugins/check_swap.c
tmp_KB changed from float to uint64, so change the sscanf format accordingly.
=> fix parsing swap values

plugins/check_swap.c
Fixes several compiler warnings for check_swap + some whitespace fixes
=> Check swap compiler warnings

plugins/check_ntp.c
compiler told me this variable was unused, so I removed it.
Also formatted the code and fixed a typo
=> Check ntp remove unused variables

plugins/check_load.c, plugins/t/check_load.t
=> Display total and scaled load values if check_load scales the values by number of CPUs

.github/prepare_debian.sh, .github/workflows/test.yml
Fixes some warning about actions.
And formats the prepare debian script differently (should make it easier to modify it in the future)
=> Update GitHub runner

.github/workflows/test.yml, plugins/check_curl.c, plugins/t/check_curl.t
If an IPv6 address is give as `server_address` it must be surround by square brackets.
=> Check curl detect ipv6

plugins/check_snmp.c, plugins/tests/check_snmp.t, plugins/tests/check_snmp_agent.pl
Add multiplier to modify current value.
Updated version of #1542 and might be solved #1468 too.
=> add 'multiplier' to modify current value

plugins/check_http.c, plugins/tests/check_curl.t, plugins/tests/check_http.t
So, my take on implementing chunked encoding for check_http.
Tell me, where it's broken.
fix #1533
also related to #994
fix #1122
=> Check http chunked encoding

.github/prepare_debian.sh
(due https://lists.debian.org/debian-devel-announce/2023/02/msg00000.html)
=> CI: Adding non-free source list (Closes: #1837)

plugins/sslutils.c
=> fallback to SSL_CTX_use_certificate_file for gnutls

plugins/check_procs.c, plugins/tests/check_procs.t
Signed-off-by: Christian Kujau <lists@nerdbynature.de>
=> check_procs: Implement --exclude-process to exclude specific processes

plugins-scripts/check_log.sh, plugins-scripts/check_oracle.sh, plugins-scripts/check_sensors.sh
=> fixed the outputs of the --versions options on 3 scripts

lib/utils_base.c, plugins-root/check_dhcp.c, plugins/check_curl.c, plugins/check_http.c, plugins/runcmd.c
Parts of #1848
Easier to digest :-)
=> Compiler warning part 1

plugins-root/check_dhcp.c, plugins-root/check_icmp.c, plugins/check_curl.c, plugins/check_dbi.c, plugins/check_fping.c, plugins/check_hpjd.c, plugins/check_http.c, plugins/check_ntp_peer.c, plugins/check_smtp.c, plugins/check_snmp.c, plugins/check_ups.c
Parts of #1848
Easier to digest :-)
=> Compiler warning part 2

.github/workflows/test.yml
I've prepared a draft to detect missing translation updates in a way. I don't know if that's the golden way ... but it's a starting point.
=> Try to detect if there are translation updates via CI

plugins/check_dbi.c
Parts of #1848
Easier to digest :-)
Fixing function deprecations in libdbi
=> Try fixing deprecated functions in libdbi

.github/workflows/test.yml, configure.ac, plugins/check_swap.c
=> Changing remaining sscanf format specifier to unsigned long

po/de.po, po/fr.po
sorry about that. Should have let the test case run through
=> Fix error in translation file introduced during a merge

doc/developer-guidelines.sgml
This PR intends to update the development documentation a little in regard of more or less recent changes.
* Recommend strongly the use "real" booleans instead of just using numbers
* Allow the usage of the C++ style comments.
=> Update docs regarding C coding style

.github/workflows/test.yml
=> run tests with debian:stable

.github/workflows/test.yml, m4/np_mysqlclient.m4, plugins/check_ntp.c, plugins/t/check_imap.t, plugins/t/check_users.t, plugins/tests/check_curl.t
Somehow codespell finds them just now.
=> Fix some more typos

plugins-scripts/check_disk_smb.pl
patch by Marek Marczykowski marmarek@staszic.waw.pl
originated from pld-linux
https://github.com/pld-linux/monitoring-plugins/commits/auto/th/monitoring-plugins-2.1.2-1/nagios-plugins-check_disk_smb-zero-cap.patch
=> check_disk_smb: allow checking 0-sized resource (ex. IPC$)

plugins-root/check_dhcp.c, po/de.po, po/fr.po, po/monitoring-plugins.pot
- added dhcp rogue detection contributed by Patrick Cervicek (patrick AT cervicek.de)
- closes #752
replaces #1375 
reopened this to fix merge conflicts
=> check_dhcp: merged patch from #752

plugins/check_curl.c
Fixes for `CFLAGS="-Wcast-function-type"`
=> check_curl: Compiler warnings cast function type

.github/workflows/test.yml
add some more steps to the test pipeline:
- make dist
- builds from the tarball above
this test should fail until #1943 is fixed.
=> extend github action tests

plugins-scripts/check_oracle.sh
=> Shellcheck fixes for check_oracle

plugins/check_ups.c
Hi,
This adds support for the _ups.realpower_ variable which contains the output power of the UPS.
The output looks like this on my system:
```
UPS OK - Status=Online Utility=221.0V Batt=87.0% Load=32.0% Real power=255.0W |voltage=221000mV;;;0; battery=87%;;;0;100 load=32%;;;0;100 realpower=255W;;;0;
```
I'm not sure whether we should have "Real power" or "Realpower" in the human-readable output, please let me know what the preferred form is.
=> check_ups: output ups.realpower if supported

.github/workflows/test.yml
=> CI: Switch back to testing

plugins/check_procs.c
Also reindent the code, converting stray tabs to 2 spaces.
This is a "companion" PR to https://github.com/monitoring-plugins/monitoring-plugins/pull/1968
=> check_procs: Improve help text, mentioning excluded processes

plugins-root/check_dhcp.c, plugins/check_http.c, plugins/check_snmp.c, plugins/popen.c, plugins/runcmd.c
Some more compiler warnings :-)
=> Compiler warning part 7

plugins/check_curl.c
This PR adds a new `--haproxy-protocol` flag to `check_curl`.
The new flag enables the libcurl option `CURLOPT_HAPROXYPROTOCOL` to send haproxy protocol header v1 at the beginning of the connection.
=> check_curl: add haproxy protocol option

lib/parse_ini.c
Avoid freeing symbols from text section by remembering where they are from
=> Ini Parser: Avoid freeing symbols from text section

plugins/negate.c
This commit updates the negate plugin's helptext as it is currently ambiguous.
=> Improve negate plugin helptext

plugins-scripts/check_ircd.pl
The prior bindRemote function was restricted to IPv4 by explicitly using address family specific functions as pack_sockaddr_in or unparametrized gethostbyname. Since Perl 5.14, released in early 2013, there is IO::Socket::IP, which supports lookups and connects for a dual stacked network.
By switching the connection establishment code, the plugin is now able to establish connections to IPv6-only hosts. Furthermore, additional -4 and -6 flags were introduced to enforce a specific address family.
> $ netstat -p tcp -ln | grep 6667
> tcp6         0      0  *.6667                 *.*                    LISTEN
> $ ./plugins-scripts/check_ircd -H localhost
> IRCD ok - Current Local Users: 4
> $ ./plugins-scripts/check_ircd -H localhost -4
> IRCD UNKNOWN: Could not start socket (Connection …
=> check_ircd: IPv6 support

plugins/check_curl.c, plugins/check_http.c
=> Small check_curl fixes

plugins/check_curl.c
This change aims to raise the worst status between the SSL check and the HTTP check.
before:
check_curl -H www.google.fr -S --continue-after-certificate --certificate 4000,4000 ; echo $? CRITICAL - Certificate '*.google.fr' expires in 74 day(s) (Tue 22 Oct 2024 12:53:52 PM GMT +0000). HTTP OK: HTTP/2 200  - 22807 bytes in 0.076 second response time |time=0.075516s;;;0.000000;10.000000 size=22807B;;;0; 0
after:
/usr/lib/nagios/ovh/check_curl -H www.google.fr -S --continue-after-certificate --certificate 4000,4000 ; echo $? CRITICAL - Certificate '*.google.fr' expires in 74 day(s) (Tue 22 Oct 2024 12:53:52 PM GMT +0000). HTTP OK: HTTP/2 200  - 22840 bytes in 0.090 second response time |time=0.090463s;;;0.000000;10.000000 size=22840B;;;0; 2
=> check_curl: raise SSL issue when --continue-after-certificate is used

plugins/check_disk.c
Same as #2020 but for `check_disk`
=> Check disk static fixes

CODING, doc/developer-guidelines.sgml
https://github.com/monitoring-plugins/monitoring-plugins/pull/2026#issuecomment-2413039870
=> Docs update

.clang-format, plugins-root/check_icmp.c
* apply clang-format
* mark global variables correctly as `static`
* update copyright
=> Cleanup check icmp

plugins/check_apt.c, plugins/check_http.c, plugins/check_ide_smart.c, plugins/check_ldap.c, plugins/check_mysql.c, plugins/check_nt.c, plugins/check_ntp.c, plugins/check_ntp_time.c, plugins/check_nwstat.c, plugins/check_overcr.c, plugins/check_pgsql.c, plugins/check_ping.c, plugins/check_procs.c, plugins/check_radius.c, plugins/check_real.c, plugins/check_smtp.c, plugins/check_snmp.c, plugins/check_ssh.c, plugins/check_tcp.c, plugins/check_time.c, plugins/check_ups.c, plugins/check_users.c, plugins/negate.c, plugins/netutils.c, plugins/picohttpparser/picohttpparser.c, plugins/popen.c, plugins/runcmd.c, plugins/sslutils.c, plugins/urlize.c, plugins/utils.c
On several plugins:
* clang-format
* update copyright
* some linter fixes
=> Cleanup for some more plugins

plugins/check_disk.c
#2038 but with more variables :-)
=> check_disk: Initialize most variables

plugins/check_fping.c
Fixes #2040 - this adds dontfrag and random flags to the check_fping tool.
=> Add dontfrag / random to fping check

tap/tap.c, tap/tap.h, tap/tests/diag/test.c, tap/tests/fail/test.c, tap/tests/ok/ok-hash/test.c, tap/tests/ok/ok-numeric/test.c, tap/tests/ok/ok/test.c, tap/tests/pass/test.c, tap/tests/plan/no-tests/test.c, tap/tests/plan/no_plan/test.c, tap/tests/plan/not-enough-tests/test.c, tap/tests/plan/sane/test.c, tap/tests/plan/skip_all/test.c, tap/tests/plan/too-many-plans/test.c, tap/tests/plan/too-many-tests/test.c, tap/tests/skip/test.c, tap/tests/todo/test.c
clang-format everything in the tap folder.
=> tap: clang-format

plugins/check_fping.c
Due to a mistake with git the command line args were not properly updated.
Really sorry they were missed. I also took the chance to fix the "check_disk" in the header. 
Outside of that, it's working happily in my nagios setup :)
=> Add missed changes for dontfrag

plugins/check_by_ssh.c
=> Check by ssh missing options

NPTest.pm
=> Just use eval instead of Try::Tiny in tests

.github/os_detect.sh
=> CI: Install gawk on fedora > 41

plugins-root/check_icmp.c, plugins-root/check_icmp.d/check_icmp_helpers.c, plugins-root/check_icmp.d/config.h
Some more adjustements to check_icmp which were leftover from #2125.
Noticable:
- General corrections/improvements to help output
- Parameter to choose the output format
- Introduce long options to be more similar to other plugins
=> Check icmp/adjustements

.github/workflows/codeql-analysis.yml, .github/workflows/spellcheck.yml, .github/workflows/test.yml
This PR adds a manual dispatch to all workflows
=> CI: Adding workflow_dispatch
