monitoring-plugins/monitoring-plugins

- plugins/check_fping.c
Stole the logic in check_ping that allows it to autodetect whether an
address is ipv6 or not. Now the user does not have to specify -6 when
using check_fping with ipv6 addresses.
> check_fping: autodetect ipv6 addresses

- plugins/check_http.c
Ported the fix from Frank4dd to the latest git version. See also http://nagios.frank4dd.com/howto/monitor-ssl-websites-through-proxy.htm
> check_http: Adding support for checking SSL-Websites through Proxies

- NEWS
- plugins/check_http.c
- plugins/netutils.h
- plugins/sslutils.c
check_http's `-S`/`--ssl` option now allows for requesting the TLSv1.1 and TLSv1.2 protocols.  Apart from that, a `+` suffix can be appended in oder to also accept newer protocols than the specified version (e.g., `--ssl=1.1+` to accept TLSv1.1 and TLSv1.2).
> check_http: Allow for requesting TLSv1.1 and TLSv1.2

- plugins/check_smtp.c
currently STARTTLS check does not work with -e if there's text like '220 hostname ESMTP*'. This is caused by SMTP answer from host. 
Postfix answer: 220 2.0.0 Ready to start TLS
Exchange 2010: 220 2.0.0 SMTP server ready
This fix checks against 220 and closes #1093
> check_smtp.c: modified SSL check for use with -e

- plugins-root/pst3.c
On Solaris, check_procs uses pst3 instead of /bin/ps (see
http://monitoring-plugins.org/doc/faq/ps-on-solaris.html for background). There's
a small bug in pst3 which causes it to NOT report some processes that are at
the end of the process table, at least on very busy systems (we noticed this
on a CoolThreads T5240 with load averages up to 90).
The bug is that a filehandle is not properly closed.
Thanks to jwinkle01 for finding and patching the bug.
(Closes #1203)
> check_procs: Fix for unclosed filehandle in pst3 on Solaris

- plugins/check_dns.c
Thus recent Versions of bind will no longer change .IN-ADDR.ARPA to lowercase
as the uppercase version is also valid.
To have check_dns.c consider this fact change strstr to strcasestr
> DNS is case insensitive!

- plugins/check_dig.c
check_dig was casesensitive if an expected answer is given.
Switching strstr with strcasestr fixes this issue
While testing i noticed a bug where expected is not an exact match
New issue for that is opened #1385
This fix closes #1233
> check_dig: expected answer is now incasesensitive

- plugins/check_ntp_time.c
> check_ntp_time: remove unused variables

- plugins/check_ntp.c
> check_ntp: remove unused variables

- plugins/check_ide_smart.c
Remove function unused since commit b5cc292.
Signed-off-by: Sebastian Herbszt <herbszt@gmx.de>
> check_ide_smart: remove unused function

- plugins/check_dig.c
After upgrading from an Ubuntu/15.10 to 16.04 installation, I noticed that
check_dig is always returning a WARNING:
$ /usr/lib/nagios/plugins/check_dig -l localhost -v
/usr/bin/dig   -p 53 @127.0.0.1 localhost A +tries=3 +time=6
Looking for: 'localhost'
DNS WARNING - 0.008 seconds response time (dig returned an error status)|time=0.008274s;;;0.000000
The older Ubuntu installation got its check_dig from the
nagios-plugins-standard package[0] which did not include the +tries
option. The current Ubuntu version provides its check_dig from the
monitoring-plugins-standard package[1], which _does_ use the +tries
option that was introduced with df53473[2].
On my system, it so happens that /usr/bin/dig is provided not by the
(BIND) dnsutils package but by knot-dnsutils[3] from the Knot DNS …
> check_dig: use +retry instead of +tries

- configure.ac
- plugins/check_http.c
- plugins/check_smtp.c
- plugins/check_tcp.c
- plugins/common.h
changes:
- CRYPTO_lock detection replaced in configure.ac. We don't use that
function anywhere, so just replace it with the suggested one from
https://wiki.openssl.org/index.php/Library_Initialization#Autoconf
- OPENSSL_NO_SSL2 is no longer defined while ssl2 is not included.
Set it ourself using the suggested openssl 1.1 version check from
https://wiki.openssl.org/index.php/1.1_API_Changes#Backward_compatibility
- openssl 1.1 sends a sigpipe if the connection is still open when
calling SSL_shutdown(), so move the close before the shutdown.
> add openssl 1.1 support

- plugins/check_disk.c
This fix changes output of check_disk in case of --error-only/-e option
is used and state is ok
- Old output: DISK OK
- New output: DISK OK - free space: / 159731 MB (83% inode=61%);
/dev/shm 2926 MB (100% inode=99%); /boot 58 MB (32% inode=99%);
Resolves: #1420
> check_disk - show all disks if state is ok and option error only is used

- plugins/check_http.c
Added socket_timeout to time\* perfdata values, see issue #1350
**Then**
```
./check_http -H 127.0.0.1 -t 30 -E
HTTP OK: HTTP/1.1 200 OK - 380 bytes in 1,334 second response time |time=1,334256s;;;0,000000 size=380B;;;0 time_connect=0,000235s;;;  time_headers=0,000029s;;; time_firstbyte=1,333924s;;; time_transfer=1,333947s;;;
./check_http -H 127.0.0.1 -t 30
HTTP OK: HTTP/1.1 200 OK - 380 bytes in 0,001 second response time |time=0,000551s;;;0,000000 size=380B;;;0
```
**Now**
```
./check_http -H 127.0.0.1 -t 30 -E
HTTP OK: HTTP/1.1 200 OK - 380 bytes in 0,006 second response time |time=0,005946s;;;0,000000;30,000000 size=380B;;;0 time_connect=0,000059s;;;;30,000000  time_headers=0,000035s;;;;30,000000 time_firstbyte=0,005737s;;;;30,000000 time_transfer=0,005806s;;;;30,000000
./check_http …
```
> check_http: added timeout to perfdata as max val

- plugins-scripts/check_mssql.pl
alarm timeout now uses -t option, closes #991
If not set, default TIMEOUT from utils.pm will be used
```
$timeout = $TIMEOUT unless (defined($timeout))
```
> check_mssql.pl: switched alarm timeout

- plugins/check_smtp.c
expect option (-e) supported only first response, so checking for any other response e.g. 250-xxx would never match. 
This fix stores response of first buffer and compares against
closes #1381
> check_smtp: extended support for expect option

- plugins-root/check_dhcp.c
As per the comment in the logged issue, this fixes #1450.
> properly remove MSG_PEEK in check_dhcp.c.

- plugins/check_dns.c
small change to allow the use of check_dns for IPv6-RDNS. Currently only IPv4 is supported.
> check_dns: allow for IPv6 RDNS

- NEWS
- THANKS.in
- plugins/check_dns.c
- plugins/t/NPTest.cache.travis
- plugins/t/check_dns.t
Improve `check_dns` by allowing the _expected address_ to be specified by CIDR notation (IPv4 only).
> check_dns: Accept CIDR

- plugins/check_apt.c
- plugins/t/check_apt.t
The check_apt plugin returns WARNING if there are any updates available, and CRITICAL if there are security updates. While security updates are indeed important, non-critical updates are usually not considered a problem. However, there plugin does not offer a way to adjust the warning threshold.
This patch adds a switch, --only-critical, that makes the plugin return OK in case there are only non-critical updates.
> check_apt: Add --only-critical switch

- .travis.yml
- plugins-scripts/check_disk_smb.pl
- plugins/t/NPTest.cache.travis
- plugins/t/check_disk.t
- plugins/t/check_http.t
- plugins/t/check_snmp.t
- plugins/t/check_tcp.t
- plugins/t/check_udp.t
- check_disk_smb did not exit cleanly on timeouts.
- snmp tests failed with systemd
- replace hardcoded verisign.com tests with localhost tls apache
> make tests more reliable

- plugins-scripts/t/utils.t
utils.pm uses relative include ".." but the path is relativ to the current folder, so it
does not work when running "perl t/utils.t". Just add another lib of "." fixes that. We could
use FindBin but we don't want to make it unnecessarily complicated.
> script tests: fix relative lib path in utils test

- .travis.yml
- plugins-scripts/check_file_age.pl
- plugins-scripts/t/check_file_age.t
Useful when a regular process overwrites a file showing the current status. In my use case, the error output from a regular rsync so I can check there were no errors
> Enable check_file_age to test for maximum file size

- plugins/check_dig.c
This fixes a minor spelling issue. The localization files need to be adjusted accordingly, but I couldn't find any documentation on how to update the pot file and didn't want to do this by hand.
> plugins: check_dig: Fix spelling

- plugins/negate.c
Output plugin's stderr to stderr and do  not exit with WARNING in that case
> Output plugin's stderr to stderr

- plugins/common.h
As of 10.2 MariaDB no longer defines MYSQL_PORT.
> Fix build issue with MariaDB 10.2

- lib/utils_base.c
The die function is called with NULL as second argument in https://github.com/madpilot78/monitoring-plugins/blob/master/plugins/check_http.c#L939.
I'm almost sure that passing a NULL as the format string to printf functions falls in the undefined behavior category. In FreeBSD this causes a segmentation fault.
This simple patch checks for fmt not to be NULL and only it is not NULL proceeds to call the vprintf.
It avoids the segmentation fault on my systems.
> Avoid passing NULL to vprintf().

- .travis.yml
- plugins/check_http.c
- plugins/t/NPTest.cache.travis
- plugins/t/check_http.t
- tools/squid.conf
Simple format, avoids refactoring the CONNECT feature.
fixes #1475
> Allow user to specify HTTP method after proxy CONNECT

- plugins/check_http.c
This should help with figuring out ia problem at a glance when enabled for
healthz endpoints on web APIs, for example.
The content of the body can point to what the problem is and help with
diagnostics.
Fixes #1559
> Add new flag --show-body/-B to print body

- plugins/check_hpjd.c
Many organisations let the users refill the papers. so they are not interested if a printer is "out of paper". This commit adds a flag, -D that disables warnings on this particular printer status.
> check_hpjd: Added -D option to disable warning on 'out of paper'

- plugins/check_smtp.c
In Debian we got reported this issue: https://bugs.debian.org/886888
The check_smtp command has a bug when both SSL is enable and check
command (-C) are passed.
The code for check commands is:
```
while (n < ncommands) {
xasprintf (&cmd_str, "%s%s", commands[n], "\r\n");
my_send(cmd_str, strlen(cmd_str));
…
```
And this works when SSL is not used, because n in initialized at the
start of main, and not used until this block. However, when SSL is
enabled, n is assigned the size of the server's second EHLO response (I
think in bytes), which will usually be significantly higher than the
command passed. As such, no commands are executed and no responses are
checked, which - silently - defeats the desired checks and results in a
success value.
Attached a trivial patch which simply initializes n …
> Simply initializes n before it is used

- plugins/tests/check_snmp.t
The check_snmp rate tests depend on the exact amount of time spend between the
plugin runs and will fail on busy machines, ex. the ci servers. Using faketime
mitigates this issue and also removes all the sleeps.
> tests: make check_snmp test more reliable

- NEWS
- THANKS.in
- plugins/check_dns.c
Improve the handling of multiple IPs in check_dns: my use case is a set of hosts with 2 addresses each (IPv4 + IPv6), which I don't want to split into "IPv4 is smaller in string compare than IPv6" and "the others". And I want to check that the exactly the addresses I have configured are returned, no more, no less.
This more or less intentionally breaks the previously working "pass addresses as comma separated string and compare that". The combination of -L and multiple -a does the same without breaking randomly on every IP change. I don't care. YMMV.
> check_dns: improve support for checking multiple addresses

- plugins/check_http.c
This PR is a follow-up to PR #1560 
We discovered that in the spaghetti of check_http, if an `--expect` parameter is specified, the code does `die()` before the body is appended.
This commit appends the body also when expect is used.
Problem:
**good**
```
/check_http -H iovation-api.example.com -u /health/check -B 
HTTP CRITICAL: HTTP/1.1 500 Internal Server Error - 206 bytes in 0.018 second response time |time=0.017735s;;;0.000000;10.000000 size=206B;;;0
The last 20 call to Iovation failed
```
**bad**
```
HTTP CRITICAL - Invalid HTTP response received from host: HTTP/1.1 500 Internal Server Error
```
> Also support the --show-body/-B flag when --expect is used

- plugins/check_dns.c
Sorry, once things got merged I noticed that I missed a word in the parameter description.
> check_dns: fix typo in parameter description

- plugins-root/check_icmp.c
https://github.com/monitoring-plugins/monitoring-plugins/pull/1384 got stuck some while ago, and needed to be rebased on the latest master to pass the tests. The original branch for the PR is gone, so had to create a new one.
All credits to @LarsMichelsen 
> This commit adds IPv6 capabilities to check_icmp. It is now possible to
> specify the address family using the arguments -4 (default) or -6.
> 
> To make the change possible we had to move the argument parsing previous
> to creating the socket to be able to create it with the correct address
> family.
> 
> This commit also fixes some gcc 4.9.2 compiler warnings. It has been
> tested with several current linux distributions (debian, ubuntu, rh,
> sles).
> 
> This commit fixes #1291
> check_icmp: Add IPv6 support

- lib/utils_base.c
- lib/utils_base.h
- lib/utils_cmd.c
- lib/utils_cmd.h
- plugins/check_dbi.c
- plugins/check_pgsql.c
- plugins/common.h
- plugins/popen.c
- plugins/runcmd.c
- plugins/utils.c
- plugins/utils.h
When check_by_ssh runs into a timeout it simply exits keeping all child processes running.
Simply adopting the kill loop from runcmd_timeout_alarm_handler() fixes this.
> check_by_ssh: fix child process leak on timeouts

- gl/fsusage.c
- gl/fsusage.h
- lib/utils_disk.c
- lib/utils_disk.h
- plugins/check_disk.c
This is not enabled by default
It can be enabled with the -P (--iperfdata) option
Of cause, option names can be changed, and it can be enabled by default if you think it would be a good thing.
Regards,
Vincent
> [check_disk] add support to display inodes usage in perfdata

- plugins/check_snmp.c
Previously it was unclear that when setting a timeout using -t it is not the final timeout interval in check_snmp.
The final timeout interval is calculated using "timeout_interval * retries + 5" it seems.
This PR makes this more clear in the help output.
> check_snmp: make calcualtion of timeout value in help output more clear

- configure.ac
- plugins/check_load.c
```
-W, --print-top-warning
Print top consuming processes on WARNING status
-C, --print-top-critical
Print top consuming processes on CRITICAL status
-n, --procs-to-show=NUMBER_OF_PROCS
Number of processes to show when printing top consuming
processes. Not useful without -W or -C. Default value is 5
```
> Adding print top consuming processes option to check_load

- plugins/check_apt.c
This option specifies the minumum number of packages available for upgrade to return WARNING status. Default is 1 package.
> Adding packages-warning option to check_apt plugin

- plugins/check_mysql.c
The help text says that -H accepts a "unix socket (must be an absolute
path)". Now that actually corresponds to reality.
Signed-off-by: Robin Sonefors <robin.sonefors@op5.com>
> check_mysql: Allow sockets to be specified to -H

- plugins/check_swap.c
If run with "-n ok" a host which ran completely out of swap space would return "ok" which is
not desired. It should only return "ok" if there is no swap space configured at all.
> check_swap: repaired "-n" behaviour

- plugins/popen.c
- plugins/runcmd.c
- plugins/utils.c
- plugins/utils.h
If _SC_OPEN_MAX is available then maxfd was zero initialized and never set to the value from sysconf.
This leads to segfaults with free(): invalid size.
> fix maxfd being zero

- plugins/popen.c
- plugins/popen.h
There are different declarations/definitions for `timeout_interval`:
`lib/utils_base.c` has the definition:
```c
unsigned int timeout_interval = DEFAULT_SOCKET_TIMEOUT;
```
`lib/utils_base.h` has the appropriate declaration:
```c
extern unsigned int timeout_interval;
```
`plugins/popen.h` has an extra declaration:
```
extern unsigned int timeout_interval;
```
This doesn't hurt, but it's a dupe. The one in `utils_base.h` should be enough, so remove this one.
`plugins/popen.c` has a WRONG one:
```c
extern int timeout_interval;
```
Remove it!
Use `#include "utils.h"` to get the right one.
This makes the local defines for `max`/`min` unnecessary, so remove them also.
> Fix timeout_interval declarations

- plugins-root/check_dhcp.c
Otherwise, it writes sizeof(size_t) bytes to &oldlen, smashing the stack.
Found on OpenBSD, but applies to all BSDs (oldlen sysctl(3) argument is size_t everywhere).
> Use size_t instead of int when calling sysctl(3).

- doc/developer-guidelines.sgml
This reverts commit 7693af147926d0eb7369a43070d114b6bd79dc70.
Now it is wrong:
After reading
https://www.naemon.org/documentation/usersguide/pluginapi.html#plugin_output_spec
the old wording makes more sense.
> Revert "simplify documentation"

- plugins/check_dns.c
- detect unreachable dns service in nslookup output (from bind-utils-9.8.2)
Fixes #1610 
- prevent core if error_scan detects an error in a line without ':'
> detect unreachable dns service in nslookup output

- plugins/check_http.c
Added the proxy authorization and extra Headers for the case when check_http is used through a PROXY for a HTTPS url through CONNECT
LINKED to the ISSUE : https://github.com/monitoring-plugins/monitoring-plugins/issues/1515
> Proxy authorization is now kept when using PROXY + CONNECT to HTTPS

- plugins-scripts/check_mailq.pl
with https://github.com/monitoring-plugins/monitoring-plugins/issues/381 -W and -C have been removed. It
would have been sufficient to only remove the long options. Restoring short options..
- fixes https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=954961
> check_mailq: restore accidentially removed options

- plugins-root/check_icmp.c
There is a small typo in plugins-root/check_icmp.c.
Should read `conspicuously` rather than `conspicuosly`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, conspicuosly -> conspicuously

- plugins/check_curl.c
- help messages fix: 1.3 in SSL version for TLSv1.3
- fixed URI buffer overflow
- fix #1665 (printing HTTP protocol version correctly as HTTP/2)
> check curl bugfixes

- plugins/check_curl.c
- plugins/tests/check_curl.t
check_curl crashes when a (broken) http server returns invalid http header with
leading spaces or double colons. This PR adds a fix and a test case for this.
> fix check_curl crash if http header contains leading spaces

- plugins/check_curl.c
- plugins/t/check_curl.t
Currently check_curl uses the libcurl function `curl_easy_strerror()` to convert from error codes to error messages. This function does not provide real context but rather returns a fixed string based on the error code. A much more accurate and user-friendly error code is available via the `CURLOPT_ERRORBUFFER` option. This PR tries to use the error message from that option where possible, falling back to the former in case it is not available.
For more details see:
https://curl.se/libcurl/c/curl_easy_strerror.html
https://curl.se/libcurl/c/CURLOPT_ERRORBUFFER.html
```
$ check_curl -H expired.badssl.com -S --ca-cert=/etc/ssl/certs/ca-certificates.crt
HTTP CRITICAL - Invalid HTTP response received from host on port 443: cURL returned 60 - Peer certificate cannot be authenticated with given …
```
> Update check_curl.c to display a specific human-readable error message where possible

- plugins/check_pgsql.c
As strcpy may overflow the resulting buffer:
flo@p5:~$ /tmp/f/usr/lib/nagios/plugins/check_pgsql -d "$(seq 1 10000)"
*** buffer overflow detected ***: terminated
Aborted
I would propose to change the code rather like this, using snprintf
which honors the buffers size and guarantees null termination.
> Using snprintf which honors the buffers size and guarantees null temination. (Closes: #1601)

- plugins/check_snmp.c
Hi,
`
OMD /tmp$ /omd/sites/nonprod/lib/nagios/plugins/check_snmp -H razormail1 -o 1.3.6.1.4.1.3246.2.2.1.4.3.1 -n -C 'public' -P 2c -w 100 -c 100 -l 'Mail queue length' -vv
/bin/snmpgetnext -Le -t 10 -r 5 -m '' -v 2c [context] [authpriv] razormail1:161 1.3.6.1.4.1.3246.2.2.1.4.3.1
iso.3.6.1.4.1.3246.2.2.1.4.3.1.0 = Counter32: 0
SNMP OK - Mail queue length 0 | 'Mail queue length'=0;100;100c 
`
The "c" does not belong at the end of the perfdata string. It must be _'Mail queue length'=0c;100;100_
Gerhard
> check_snmp: put the "c" (to mark a counter) after the perfdata value

- plugins/check_http.c
Happened to have a regexp hitting the 256 limit, please consider increasing the limit. Thank you.
> plugins: check_http: Increase regexp limit

- plugins/check_http.c
You need to read the docs carefully to realize that check_http has two 
modes of operation: the regular HTTP checks, and a TLS certificate 
check. Only one of these can be run in a single invocation.
Fixes #1553
> Docs check_http: make -C obvious

- plugins/check_curl.c
- plugins/t/check_curl.t
One of the major considerations for moving to check_curl is the ability to verify peer certificates automatically, using the system CA settings (i.e. the default curl behaviour). While maintaining backwards compatibility is necessary for a drop-in replacement of check_http, it would be nice to have an option to reactivate certificate verification without having to specify a CA chain.
The new option is `-D` or `--verify-cert`
```
$ check_curl -H expired.badssl.com -S
HTTP OK: HTTP/1.1 200 OK - 761 bytes in 0.767 second response time |time=0.766678s;;;0.000000;10.000000 size=761B;;;0
$ check_curl -H expired.badssl.com --ca-cert=/etc/ssl/certs/ca-certificates.crt
HTTP CRITICAL - Invalid HTTP response received from host on port 443: cURL returned 60 - SSL certificate problem: certificate has …
```
> Add an option to check_curl to verify the peer certificate & host using the system CA's

- plugins/check_curl.c
```
$ check_curl -H www.kupujemprodajem.com -S --no-body -v
> GET / HTTP/1.1
Host: www.kupujemprodajem.com
User-Agent: check_curl/v2.3.1 (monitoring-plugins 2.3.1, libcurl/7.58.0 OpenSSL/1.1.1 zlib/1.2.11 libidn2/2.0.4 libpsl/0.19.1 (+libidn2/2.0.4) nghttp2/1.30.0 librtmp/2.3)
Accept: */*
Connection: close
< HTTP/1.1 200 OK
< Server: nginx
< Date: Mon, 12 Apr 2021 16:11:24 GMT
< Content-Type: text/html; charset=UTF-8
< Connection: close
< Vary: Accept-Encoding
< HTTP_X_FORWARDED_PROTO: https
< HTTP_X_FORWARDED_FOR:
< Set-Cookie: KUPUJEMPRODAJEM=b94idrr7k9leldjp5gh23b9ugr; path=/; domain=.kupujemprodajem.com; HttpOnly
< Set-Cookie: machine_id=8f910d26570f22b0f9aad3422d86fddb; expires=Fri, 11-Jun-2021 16:11:24 GMT; Max-Age=5184000; path=/; domain=.kupujemprodajem.com
< Set-Cookie: …
```
> check_curl: Fix bug where headers beginning with HTTP_ cause the status line parsing to fail

- plugins/check_curl.c
- added verbose output in verify_callback
- pin refcounting for certs (avoid subject extraction error when checking
certs in is_openssl_callback mode)
> fixes check_curl: "CRITICAL - Cannot retrieve certificate subject."

- plugins/check_by_ssh.c
Removes host check from the plugin and lets SSH decide if the hostname parameter is valid.
SSH will additionaly search the config file for the name and therefore allow some customization.
#1135
> Let ssh decide if a host is valid, enables usage of ssh .config file

- plugins/check_http.c
We use the check_http in our Icinga instance and once had the case that we got the message (HTTP WARNING - redirection creates an infinite loop) issued with the warning status. Since this is an infinite loop message I think the state should be rather 'critical', right?
> check_http: changed 'STATE_CRITICAL' to 'STATE_WARNING' for infinite loop

- plugins/check_curl.c
- adds --automatic_decompression for automatically decompressing the body
- bugfixes:
- certificate check with old OpenSSL versions (up_ref pining)
- DNS cache with host:port:host is no longer allowed in newest curl version, must be host:port:ip (leads to an error
in HTTPS virtual host cases)
- the usual scoping and buffer overflow bugfixes
- backports from check_http:
- infinitite redirection loops should be CRITICAL
> Feature check curl

- plugins/check_swap.c
- plugins/t/check_swap.t
- plugins/utils.c
- plugins/utils.h
The original problem was #1705 
where the performance data output of check_swap did not conform to
the parser logic of a monitoring system (which decided to go for
"correct" SI or IEC units.
The PR was accompanied by a change to byte values in the performance
data which broke the _perfdata_ helper function which could not handle
values of this size.
The fix for this, was to use _fperfdata_ which could, but would
use float values.
I didn't like that (since all values here are discreet) and this
is my proposal for a fix for the problem.
It introduces some helper functions which do now explicitely work
with (u)int64_t, including a special version of the _perfdata_ helper.
In the process of introducing this to check_swap, I stumbled over
several sections of the check_swap code which I found …
> Fix perfdata for check swap

- lib/utils_base.c
- lib/utils_base.h
- plugins/check_snmp.c
- plugins/tests/check_snmp.t
when using check_snmp with multiple oids it simply printed the unparsed content
from -w/-c into the thresholds for each oid. So each oid contained the hole -w
from all oids.
./check_snmp ... -o iso.3.6.1.2.1.25.1.3.0,iso.3.6.1.2.1.25.1.5.0 -w '1,2' -c '3,4'
before:
SNMP ... | HOST-RESOURCES-MIB::hrSystemInitialLoadDevice.0=393216;1,2;3,4 HOST-RESOURCES-MIB::hrSystemNumUsers.0=24;1,2;3,4
after:
SNMP ... | HOST-RESOURCES-MIB::hrSystemInitialLoadDevice.0=393216;1;3 HOST-RESOURCES-MIB::hrSystemNumUsers.0=24;2;4
This also applies to fixed thresholds since check_snmp translates negative infinities from: `~:-1` to `@-1:~`
> check_snmp: fix performance thresholds when using multiple oids

- plugins/check_curl.c
- plugins/t/check_curl.t
The original addition of the `-D` option to verify certificates is causing SSL to be forced into use whenever this switch is used. This fix allows the ability to toggle SSL separately from this switch (which will still verify certificates following a HTTP > HTTPS redirect).
```
$ check_curl -H neverssl.com -f curl --sni --no-body -D -t 40
HTTP CRITICAL - Invalid HTTP response received from host on port 443: cURL returned 51 - SSL: no alternative certificate subject name matches target host name 'neverssl.com'
```
```
$ check_curl -H neverssl.com -f curl --sni --no-body -D -t 40
HTTP OK: HTTP/1.1 200 OK - 473 bytes in 1.125 second response time |time=1.124970s;;;0.000000;40.000000 size=473B;;;0
$ check_curl -H neverssl.com -f curl --sni --no-body -D -t 40 -S
HTTP CRITICAL - Invalid HTTP …
```
> check_curl.c: bugfix: verify certificates option should not force SSL to be used

- plugins/check_ping.c
- plugins/utils.c
Displaying the RTA in perfdata will confuse the system using this data  and falsify averages.
> check_ping: Do not show RTA if no connection was possible

- plugins/check_snmp.c
> Fixed option description authpassword -> authpasswd + whitespaces

- plugins/check_ldap.c
It's not secure to provide LDAP password through command line option
because other users on the same host can see the password in
'ps' command output.
This change allows check_ldap to get password from environment variable.
> Allows check_ldap to read password from environment variable

- plugins/check_by_ssh.c
We need the option  to bail out with an error, if there is something on stdout.
E.g. someone is defining: 
```
stty erase ^H
```
without any checks in the users profile (.bashrc or .profile)
> check_by_ssh: added option to exit with an warning, if there is output on STDERR

- plugins/check_snmp.c
When using a large distributed network with the same group of checks used against a large number of devices, occasionally there are missing cards in a few devices that are present in other devices. Rather than having a large number of unknown results, disable active checking on those large number of result or having to create a unique check configuration for those devices.
This option allows you to select an OK, WARNING, CRITICAL or UNKNOWN status while still retaining the default behavior when not present. This also allows a for the check to immediately start checks as intended should the hardware be added that the check is looking for.
> Added option for null zero length string exit codes

- plugins/check_ping.c
Trivial source code formatting only: Use tabs consistently for source code indentation (whitespace), as per https://github.com/monitoring-plugins/monitoring-plugins/blob/master/CODING .
> Trivial source code whitespace formatting fixes to standard.

- plugins/check_fping.c
To reduce the check-duration, it addes a host-alive flag which stops testing
after the first successful reply.
> Implements 'host-alive' mode (Closes. #1027)

- plugins/check_pgsql.c
This is used in the long output instead of the actual query.
So instead of
OK - 'select stuff from various, tables where some_stuff is null and other_stuff is not null' returned 42
one can use --queryname=check_greatest_basket and it will print
OK - check_greatest_basket returned 42
That's nicer for alerting purposes, at least in our use case.
> add --queryname parameter to check_pgsql

- plugins/check_curl.c
- plugins/check_http.c
Did it for both check_http and check_curl. Only a long option (out of reasonable
short options IMHO).
> check_http and check_curl: added --max-redirs=N option (feature #1684)

- plugins/check_disk.c
Using -M should show the mountpoint instead of the device the
file system originated from.
Seems like this was not the case for a long time and now
the default is to show the mount point. Using `-M` reverts
to showing the (block) device instead.
The usage Description was adjusted with this commit.
> check_disk: Description for -M was the wrong way around

- plugins-scripts/check_uptime.pl
- plugins-scripts/t/check_uptime.t
Dear community. Dear @wopfel and @sni.
Firsts things first: Thanks a stack for conceiving and maintaining this excellent collection of monitoring plugins.
This is a humble patch for the `check_uptime.pl` sensor to make it report the system uptime in _days_ instead of _seconds_. It has been wired to a new `--days` option, in order not to change its default behavior.
The rationale is to reduce mental load for humans, when looking at the textual output of the sensor. While the _"pretty" format_ already implemented by `check_uptime.pl` has good intentions, it didn't quite nail it for us.
With kind regards,
Andreas.
---
Currently, the baseline plugin output, with no way to change it, is:
```
CRITICAL: Uptime is 38829029 seconds.
```
We also tried using both options `--for` and `--since`. …
> check_uptime: Add option to report uptime in days instead of seconds

- plugins-scripts/check_disk_smb.pl
This pull request adds a new feature to check_disk_smb: configfile. As it is possible to define a separate config file in smbclient (-s option), check_disk_smb should use this possibility as well. This allows to run checks on older Samba servers where older settings are defined on server side but today's client side configurations are incompatible. Practical example: lanman auth.
Without a separate configfile and an old Samba server requiring lanman auth, the check fails:
```
Access Denied
```
Create a special config file with different options than the default:
```
[global]
client lanman auth = Yes
client ntlmv2 auth = No
```
And then tell the plugin to use this config file:
```
Disk ok - 11.95G (39%) free on \\sambaserver\share | …
```
> check_disk_smb: Add configfile feature

- plugins-scripts/check_mailq.pl
currently, check_mailq.pl defines the C/W arg twice (slipped in in a single commit in 2020, only adding those duplicates), leading to warnings on plugin execution.
> remove duplicate W=i/C=i args in check_mailq.pl

- .github/workflows/codeql-analysis.yml
* Update QuodeQl test to version 2 to fix the complaining in the test runs ( https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/ )
* Update test machine package cache before installing stuff to avoid trying to fetch old ( and not available ) packages
> Update CodeQL and update runner before installing

- plugins-root/check_icmp.c
> check_icmp: Fix "Invalid Argument" from sendmsg() under FreeBSD 13.1 and "setsockopt failed" for TTL setting

- plugins/check_swap.c
Seems someone (me) forgot to fix the unit for totals in the perfdata, after changing things last time.
Mea culpa.
> check_swap: Fix unit for total in perfdata

- configure.ac
- pkg/solaris/solpkg
- plugins-scripts/check_sensors.sh
Fixes #1790
It seems like grep deprecates `egrep` and `fgrep` with version 3.8 ( https://savannah.gnu.org/forum/forum.php?forum_id=10227 ),
or, well, they were deprecated in 2007 and now `grep` warns the user about it (on `stderr`).
This patch replaces all occurences of `egrep` I could find with `grep -E`.
> Replace egrep with grep -E

- plugins/check_pgsql.c
In Debian we got the following [bug](http://bugs.debian.org/982847) reported:
Hi *,
to reproduce create a Database called freshports.git and try to
use it with `check_pgsql`:
```
flo@p5:/tmp/monitoring-plugins-2.3$ /usr/lib/nagios/plugins/check_pgsql -d freshports.devgit -l flo
check_pgsql: Database name is not valid - freshports.devgit
Usage:
check_pgsql [-H <host>] [-P <port>] [-c <critical time>] [-w <warning time>]
[-t <timeout>] [-d <database>] [-l <logname>] [-p <password>]
[-q <query>] [-C <critical query range>] [-W <warning query range>]
```
```
flo@p5:/tmp/monitoring-plugins-2.3$ psql freshports.devgit
psql (13.1 (Debian 13.1-1+b1))
Type "help" for help.
freshports.devgit=# \d
Did not find any relations.
freshports.devgit=# 
```
The problem is that `check_pgsql` validates the …
> check_pgsql: check of database name is too strict

- plugins/check_http.c
Resolves #1576
Trying to resolve https://github.com/monitoring-plugins/monitoring-plugins/issues/1576 . Can somebody take a look and see if it resolves the problem with very strict webservers?
> Remove superflous CRLF in HTTP-Requests in check_http

- plugins-root/check_icmp.c
- plugins/t/check_http.t
Fix parsing of the long options --help and --version. The special
handling must be done before calling getopt().
This fixes erroneous output like:
./check_icmp --version
./check_icmp: invalid option -- '-'
./check_icmp: invalid option -- 'e'
./check_icmp: invalid option -- 'r'
./check_icmp: invalid option -- '-'
./check_icmp: invalid option -- 'e'
./check_icmp: invalid option -- 'r'
Fix test plan when run with NP_INTERNET_ACCESS=no, where the correct
number of steps must be skipped.
Caused by a removed test in 65fc7064295ac70d1388fa4db4d4d2cddd531e24
> Fix check_icmp long options and check_http test plan

- lib/utils_disk.c
* PR as discussed with @RincewindsHat; fixes #1819
* proximate cause was app. that errors returned from `get_fs_usage()` were ignored
* remediation of root cause consists of adding another condition in `np_set_best_match()`: besides constituting "best" matches, eligible mount entries also have to be accessible according to `get_fs_usage()`
* in consequence, no more such errors should occur
* I have confirmed that this PR makes the original issue (in a Kubernetes environment, as described in #1819) go away; the specific output from the check now reads as follows:
```
DISK OK - free space: /var 15388MiB (25% inode=65%);| /var=46552580096B;52372596326;58919170867;0;65465745408
```
* please let me know if you intend to merge this PR into `master`, then I will also add a corresponding change …
> check_disk: Find accessible mount path if multiple are available

- plugins/check_http.c
The current implementation becomes exponentially slower with growing response size.
See also:
https://github.com/nagios-plugins/nagios-plugins/blob/release-2.4.2/plugins/check_http.c#L1199-L1204
Test:
$ mkdir web
$ nohup python3 -m http.server -d web 5080 &
$ perl -E 'say "0123456789" for (1..2_000_000)' >| web/file.txt
$ ./check_http.orig  -t 200 -v  -I localhost -p 5080 -u /file.txt > test1.txt
real    0m26.893s
user    0m12.661s
sys     0m14.221s
$ time ./check_http -t 200 -v  -I localhost -p 5080 -u /file.txt > test2.txt
real    0m0.038s
user    0m0.011s
sys     0m0.027s
$ diff -u test[12].txt
--- test1.txt   2022-12-21 14:58:28.720260811 +0100
+++ test2.txt   2022-12-21 14:58:42.640008604 +0100
@@ -7,7 +7,7 @@
STATUS: HTTP/1.0 200 OK
**** HEADER ****
Server: SimpleHTTP/0.6 …
> make check_http faster with larger files

- plugins/check_curl.c
check_curl fails on large pages:
HTTP CRITICAL - Invalid HTTP response received from host on port 5080: cURL returned 23 - Failure writing output to destination
for example trying to run check_curl on the test from #1822
I guess the idea is to double the buffer size each time it is to small. But the code exponentially grows the buffer size which works well 2-3 times, but then fails.
> check_curl: fix checking large bodys

- plugins/check_snmp.c
the multiplier function always tried to extract a number, even if the result is a string because of using a mib.
before:
```
./check_snmp -H hostname -P2c -c public -o IF-MIB::ifAdminStatus.11466 -vvv -r 0
/usr/bin/snmpget -Le -t 10 -r 5 -m ALL -v 2c [context] [authpriv] 10.0.13.11:161 IF-MIB::ifAdminStatus.11466
IF-MIB::ifAdminStatus.11466 = INTEGER: up(1)
Processing oid 1 (line 1)
oidname: IF-MIB::ifAdminStatus.11466
response:  = INTEGER: up(1)
SNMP OK - 0 | IF-MIB::ifAdminStatus.11466=0;;
```
the regexp 0 matches, even if the actual result is "up(1)".
after this patch:
```
./check_snmp -H hostname -P2c -c public -o IF-MIB::ifAdminStatus.11466 -vvv -r 0
/usr/bin/snmpget -Le -t 10 -r 5 -m ALL -v 2c [context] [authpriv] 10.0.13.11:161 IF-MIB::ifAdminStatus.11466 …
```
> fix check_snmp regex matches

- plugins-scripts/check_log.sh
- plugins-scripts/t/check_log.t
Added --exclude to exclude patterns
Cleaned up duplicated code in the args
Fixed a bug when using --all because the count always returned "1" even when nothing matched
entry=$($GREP "$query" "$tempdiff")
count=$(echo "$entry" | wc -l)
Example:
$ touch testfile
$ TEST123=$(grep 'test' testfile)
$ echo "$TEST123" | wc -l
1
> Added --exclude, cleanup args, fix -a count bug

- plugins/check_http.c
This patch should fix an error with the way memory reallocation was used, which resulted in "realloc(): invalid next size". It is not completely clear to me as to what caused this problem, but apparently one can not depend handing a pointer to "realloc(3)" and expect that it still works afterwards, but one should/must use the one returned by the function.
Also this patch replaces a variable which was used to remember the position in the array by just computing that from the current values.
> check_http: Fix memory reallocation error in chunk decoding logic

- plugins/check_curl.c
@andreasbaumann Based on the discussions on your branch https://github.com/monitoring-plugins/monitoring-plugins/commit/03f86b5d0809967855fbaafb4d600dc5b82081fa, I've created this PR which extends it to include all IPs returned by `getaddrinfo()` in the curl resolver cache. Let me know your thoughts!
Ref issue: https://github.com/monitoring-plugins/monitoring-plugins/issues/1844
```
$ plugins/check_curl -H iptest.websitenameserver.com -S -v
* getaddrinfo IPv4 address: 143.42.96.219
* getaddrinfo IPv6 address: 2a01:7e00::f03c:93ff:fefe:fbc
* curl CURLOPT_RESOLVE: iptest.websitenameserver.com:443:143.42.96.219,2a01:7e00::f03c:93ff:fefe:fbc
* curl CURLOPT_URL: https://iptest.websitenameserver.com:443/
* Added iptest.websitenameserver.com:443:143.42.96.219,2a01:7e00::f03c:93ff:fefe:fbc to DNS …
```
> check_curl.c: Include all IPs from getaddrinfo() in curl DNS cache

- THANKS.in
- plugins-scripts/check_mailq.pl
check_mailq.pl ignores the separate submission queue used in (modern?) sendmail
implementations.
For the queue output below with one message in the submission queue and no
messages in the transport queue, check_mailq.pl reports zero messages in the
queue because the request count from the last queue always overwrites previous
queues. If the sendmail MTA isn't running or has become wedged, messages will
sit in the submission queue forever.
The attached patch fixes this in a backwards compatible way (i.e., it shouldn't
Just turning attached patch of github issue #972 into a push request.
(Closes #972)
> check_mailq.pl: separate submission queue

- plugins/check_curl.c
fixed en passant.
On FreeBSD we need:
```
pkg install uriparser curl
./configure --with-libcurl=/usr/local --with-uriparser=/usr/local
```
> check_curl: including netinet/in.h (for FreeBSD), fixed an ambigous compare warning

- plugins/check_snmp.c
- if no multiplier is set, simply return the given string. Otherwise we would strip off the unit.
- if used, allocate new space to hold the result which might be larger than the initial input
> check_snmp: disable multiplier when unused

- plugins/check_nwstat.c
- po/de.po
- po/fr.po
- po/monitoring-plugins.pot
There is just that one obvious typo that bothered me.  
Here's a fix I hope (I `grep`ed for every occurrence).
> Fix 'requres' typo

- plugins/check_pgsql.c
This adds the ability to display extra output resulting from the execution of a custom query. When a second column is present in the resultset that column will be appended to the plugin output. This can be used to give greater information to the user. For example, if the check was looking for all overdue orders, the second column could be a list of their IDs so that recipients of the alert don't have to dig into the database to find that information.
> check_pgsql: Add extra output

- lib/utils_disk.c
> check_disk: Avoid mounting when searching for matching mount points

- plugins/check_mysql.c
tl;dr - in some situations MySQL might return ER_ACCESS_DENIED_NO_PASSWORD_ERROR instead of ER_ACCESS_DENIED_ERROR, and that results in error being returned even when --ignore-auth option is provided.
This patch handles the second error code and returns OK as expected.
<hr>
Below is an explanation of why that other error code might be returned.
The error code to be returned is determined here: https://github.com/MariaDB/server/blob/11.1/sql/sql_acl.h#L65
In most cases, the `passwd_used` is not 2, and ER_ACCESS_DENIED_ERROR is returned. However if authentication happens via `unix_socket` plugin, passwd_used will be set to PASSWORD_USED_NO_MENTION (2).
If the check is done using some unknown username (`nagios` for example), [MySQL will select a random …
> check_mysql: handle ER_ACCESS_DENIED_NO_PASSWORD_ERROR if ignore_auth=1

- plugins/check_disk.c
Allow users to choose SI units as the units of choice in `check_disk`
fixes #1786
> check_disk: Display SI units correctly

- plugins/check_smtp.c
- po/de.po
- po/fr.po
- po/monitoring-plugins.pot
check_smtp: Add option to prefix PROXY header
This enables checks of SMTP servers that expect the haproxy
PROXY protocol:  -o smtpd_upstream_proxy_protocol=haproxy.
Backported from nagios-plugins:
https://github.com/nagios-plugins/nagios-plugins/commit/3246efe923b5482c5024c40e593ce942e628a3cb
Compiled the code and successfully tested the new -r/--proxy option of the resulting check_smtp plugin in a live setup.
> check_smtp: Add option to prefix PROXY header

- plugins/check_smtp.c
- po/de.po
- po/fr.po
- po/monitoring-plugins.pot
Add support for SSL/TLS hostname extension support (SNI) for check_smtp
plugin.
Backported from nagios-plugins:
https://github.com/nagios-plugins/nagios-plugins/commit/9f1628f4b5525335ce1d6e48e8ac8b07d0757f82
Compiled and successfully tested new `--sni` option
> Add support for SNI in check_smtp

- plugins/check_smtp.c
- po/de.po
- po/fr.po
- po/monitoring-plugins.pot
This PR adds new flags `-s/--ssl/--tls` to use SMTP over TLS (smtps). Per default port 465 is used if one of these new flags is set.
By changing the order of code -r/--proxy can be used with -s/--ssl/--tls, too.
These combination of options were tested successfully:
```
./plugins/check_smtp -H backend-smtp.example.com --tls --proxy
./plugins/check_smtp -H backend-smtp.example.com --tls --proxy -p 587  (fails as expected)
./plugins/check_smtp -H backend-smtp.example.com --starttls -p 587 --proxy
./plugins/check_smtp -H frontend-smtp.example.com --tls
./plugins/check_smtp -H frontend-smtp.example.com --tls -p 587 (fails as expected)
./plugins/check_smtp -H frontend-smtp.example.com --starttls -p 587
```
> Add support for SMTP over TLS

- .github/workflows/test.yml
The current master version seems to introduce an issue, e. g.
codespell
Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_301f7ff6-2829-439a-bb1e-e3787b7d0b37/0567173d-ce48-4e72-bccb-2a410baeb2a3.tar.gz. return code: 2.
https://github.com/monitoring-plugins/monitoring-plugins/actions/runs/6074675443
> Use codespell-project/actions-codespell@v2

- plugins-scripts/check_ircd.pl
On some OS, sockaddr structs include a length field. Perl's pack_sockaddr_in takes this into account; the hand-rolled "pack('S n a4 x8'..." doesn't do so, resulting in connection failures.
This replaces #1463 since github doesn't let me update the original branch
> use pack_sockaddr_in rather than hand-rolled

- lib/Makefile.am
This fixes a regression which was introduced with 719e27ddc2f0b48bcd7fe5584b23e3ce83ddf291 It prevents the creation of working release tarballs with the current toolchain.
This commit add the header file maxfd.h to list of needed files.
This should then fix #1943
> Include maxfd.h in lib Makefile to fix "make dist"

- plugins/check_disk.c
- plugins/t/check_disk.t
Using --ignore-missing together with regex matching and ignore option lead
to a wrong error message.
./check_disk --ignore-missing -w 10% -c 5% -W 10% -r /dummy -i /dummy2
DISK UNKNOWN: Paths need to be selected before using -i/-I. Use -A to select all paths explicitly
The use case here is a cluster with fail-over mounts. So it is a valid situation that
the regex match does not find anything in addtition with a ignore which also does not exist.
After this patch:
./check_disk --ignore-missing -w 10% -c 5% -W 10% -r /dummy -i /dummy2
DISK OK - No disks were found for provided parameters|
In addition this PR add the `-n` alias for `--ignore-missing` and some test cases.
> check_disk: fix ignore-missing in combination with includes (fixes #1963)

- plugins/check_procs.c
On systems with higher core counts check_procs will occasionally see its own "ps" child process with a high CPU percentage and raise a false alarm.
Ignoring the child processes of check_procs prevents this from happening.
Example of such a false alert:
```
S+     109  152286  152285   6492  1040  0.0       00:00 check_procs     /usr/lib/nagios/plugins/check_procs -w 85 -c 95 --metric=CPU -T -vvvproc#=231 uid=109 vsz=6492 rss=1040 pid=152286 ppid=152285 pcpu=0.00 stat=S+ etime=00:00 prog=check_procs args=/usr/lib/nagios/plugins/check_procs -w 85 -c 95 --metric=CPU -T -vvv
not considering - is myself or gone
R+     109  152287  152286   8088  4048  200       00:00 ps              /bin/ps axwwo stat uid pid ppid vsz rss pcpu etime comm argsproc#=231 uid=109 vsz=8088 rss=4048 pid=152287 …
```
> check_procs: ignore our own children

- .github/workflows/test.yml
This switches the main testing stuff back to debian stable since testing is broken again.
I would propose to stay with this and add workflows against testing based on manual or timer based triggers on the `master` branch.
> Use debian stable for main tests again

- plugins-root/Makefile.am
Mirroring [this issue](https://github.com/nagios-plugins/nagios-plugins/issues/508), this change allows building with Homebrew by delaying when `$(LIB_CRYPTO)` is added.
> plugins-root: prevent -lcrypto from showing up in Makefile dependencies

- plugins/check_disk.c
- plugins/t/check_disk.t
Free disk percentage value was rounded to a full integer meaning it alerted about ~1% percent too early. This is about 10GB on a 1TB disk. The warning and critical thresholds already support float values, so just the percentage calculation needs to be improved.
old:
./check_disk -w 35% -c 20% -p / -f -vvv
Thresholds(pct) for / warn: 35.000000 crit 20.000000
calling stat on /
For /, used_pct=65 free_pct=35 used_units=286451 free_units=156651 total_units=443102 used_inodes_pct=11 free_inodes_pct=89 fsp.fsu_blocksize=4096 mult=1048576
Freespace_units result=0
Freespace% result=1
Usedspace_units result=0
Usedspace_percent result=0
Usedinodes_percent result=0
Freeinodes_percent result=0
DISK WARNING - free space: WARNING [ / 156651MiB (35% inode=89%)];| …
> check_disk increase alert precision

- plugins-root/check_icmp.c
- plugins-root/t/check_icmp.t
For responding hosts nothing changes:
./check_icmp -H 10.0.0.1
OK - 10.0.0.1 rta 0.336ms lost 0%|rta=0.336ms;200.000;500.000;0; rtmax=0.471ms;;;; rtmin=0.000ms;;;; pl=0%;40;80;0;100
In case the host is down, the performance data now contain 'U' according to: https://www.monitoring-plugins.org/doc/guidelines.html#AEN201
Old:
./check_icmp -H 10.0.0.99
CRITICAL - 10.0.0.99: Host unreachable @ 10.0.1.138. rta nan, lost 100%|pl=100%;40;80;0;100
New:
./check_icmp -H 10.0.0.99
CRITICAL - 10.0.0.99: Host unreachable @ 10.0.1.138. rta nan, lost 100%|rta=U;;;; rtmax=U;;;; rtmin=U;;;; pl=100%;40;80;0;100
This confuses some performance graphing tools, ex.: pnp.
> check_icmp: keep performance data order in case of none-reachable hosts

- plugins/check_swap.c
In `check_swap`:
* Replaces another fake boolean with a real one
* renames a type to be C standart compliant
* Updates Copyright
Part of #1976, but in bite size portions now.
> check_swap: replace another fake boolen and small improvements

- plugins/check_load.c
adaugherity noticed in issue #1965, that HAVE_PROC_LOADAVG is never defined since the symbol was removed from configure quite some time ago. This commit removes the dead code which would be used when the symbol would have been defined.
Part of #1966
> check_load: remove unused code

- plugins/check_swap.c
- plugins/t/check_swap.t
This PR adds the possibility to run check_swap without having to define the thresholds. Previously to that PR, check_swap could not be run without setting thresholds.
The plugin returns OK if no thresholds are defined. This can be very helpful if Swap Usage is purely monitored for informational (and observability) purposes but without any need to alert.
```
$ ./check_swap
SWAP OK - 3% free (208MB out of 8651MB) |swap=218103808B;0;0;0;9071230976
```
Thresholds still work, of course, but are not mandatory anymore:
```
$ ./check_swap -w 10% -c 5%
SWAP CRITICAL - 3% free (208MB out of 8651MB) |swap=218103808B;907123090;453561545;0;9071230976
```
As thresholds were a must before, the change from this PR will not break any existing configurations, as they already have thresholds defined.
> check_swap: Possibility to run check_swap without thresholds

- .github/prepare_debian.sh
- plugins/t/check_curl.t
- plugins/t/check_http.t
this makes tests more reliable if we test our own sites instead some 3rd party site.
> check_http: replace www.mozilla.com with monitoring-plugins.org

- plugins/check_curl.c
- plugins/tests/check_curl.t
- plugins/tests/check_http.t
Having a webserver respond with a relative redirect as for ex. in `Location: /path/to.html` check_curl would use the wrong standard http/https port instead of crafting the absolute url using the given scheme/hostname and port.
Adding a new test case for this for check_http and check_curl. check_http did it correct already, so no fix necessary there.
before:
%>./check_curl -H 127.0.0.1 -p 50493 -f follow -u /redirect_rel -s redirected -vvv
**** HEADER ****
HTTP/1.1 302 Found
...
Location: /redirect2
...
* Seen redirect location /redirect2
** scheme: (null)
** host: (null)
** port: (null)
** path: /redirect2
Redirection to http://127.0.0.1:80/redirect2
Port 80 is wrong here.
fixed:
%>./check_curl -H 127.0.0.1 -p 50493 -f follow -u /redirect_rel -s redirected -vvv
**** HEADER ****
HTTP/1.1 …
> check_curl: fix relative redirects on non-standard port

- plugins/check_curl.c
From the mere help output for -C / --certificate, I was confused about what its two integer parameters do. Unfortunately, I also missed out on the explaining examples later. Since I like to have basic documentation for each flag, I tried to make the arguments as short as possible.
The other fix was one hyphen too many for the --cookie-jar option.
> check_curl: Documentation for --certificate, --cookie-jar

- plugins/check_curl.c
I think `check_curl` should now be considered to be ready for productive usage.
> Remove experimental state from check_curl

- plugins/check_snmp.c
Functionally this changes nothing, code style these changes are an improvement in so far as this way that huge bunch of global variables are marked as "only used in this translation unit".
> Check snmp fixes

- .github/workflows/test-next.yml
this workflow runs scheduled once a week, so it does not prevent PRs from being merged but still allows us to notice if anything will go wrong with the next release.
Remove rawhide test from the mandatory tests like we did with debian testing already.
> add new github test workflow for debian:testing and fedora:rawhide

- plugins/check_curl.c
This mainly fixes a problem introduced in #2006 ( f29785f5035e489576d2ba74be774273b73dd149 ), where the option really is `state-regex` but the help says `regex-state`.
> Check curl regex state

- .clang-format
I propose to define the code style of the C part of the project in the `golang` style.
Whatever `clang-format` does with the config is the right style.
I do get annoyed everytime with mixed indentation in the code and stuff like that.
Will this totally ruin the first level of `git blame`? yes
Nonetheless it makes things better IMHO.
In addition to this change and reformatting stuff, when convenient, we should adapt all relevant documentation.
> Add clang-format config file

- .github/mock.sh
- .github/prepare_debian.sh
While trying to find the reason for failing test in other PRs I found the test scripts to be a bit too obscure and prone to fail in weird ways.
So I added some options to fail early in the pipeline if an error occurs in any of the steps and attempted to fix some common expansion problems.
Incindently this seems to fix the pipeline errors.
> Improve readability and reliability of test prepare scripts

- plugins/check_curl.c
Fixes a `printf` directive in check_curl which should be a string not a int
> Fix false formatting directive in printf

- plugins/check_curl.c
Update the list of deprecated TLS versions in the notes of `check_curl` by adding TLS 1.1 and 1.0
fixes #2048
> check_curl: update TLS notification notes

- plugins/check_curl.c
This enables us to enable curl cookie engine by specifying an empty filename as the cookie jar file.
This works, since curl's CURLOPT_COOKIEFILE option allows passing an empty string as filename, which it interprets as a request to enable the cookie processing. But since CURLOPT_COOKIEJAR would now attempt to write to a file named by an empty filename, it would break again (or at least produce a warning in verbose output).
Overall this is allows to handle checking URLs with cookie based sessions without persisting the cookies to disk, by using the curl-internal redirect following.
> check_curl: enable internal cookie handling

- configure.ac
- plugins/common.h
Apply all changes suggested by the `autoupdate(1)` tool, except for actually requiring a newer Autoconf version (some of our CI images don't offer 2.71 yet).
> Update configure.ac to Autoconf 2.71 syntax

- configure.ac
Currently, `configure.ac` performs checks for two programs,
1. snmpget
2. snmpgetnext
The second one is used by `check_snmp` only when a particular flag is passed, but in reality, `snmpgetnext` is still required because unless its `PATH_TO_SNMPGETNEXT` is defined, compilation of `check_snmp.c` will fail.
I have no idea how you might wind up with `snmpget` and not `snmpgetnext`, but at least one person has managed to do it and file a Gentoo bug about it.  To fix the issue, this PR will disable the building of `check_snmp` if `snmpgetnext` is missing. It also emits a warning in that case. For most people this should do absolutely nothing.
See also:
* https://github.com/nagios-plugins/nagios-plugins/pull/802
> Require snmpgetnext to build check_snmp

- NPTest.pm
- plugins/t/check_swap.t
Adds some logic to try to always parse the plugin output in tests as JSON.
This should remove some duplicate code from the test files and for the `check_swap` tests this is also contained in this commit
> Implement JSON output parsing for tests

- .github/workflows/test-next.yml
- .github/workflows/test.yml
Previously IPv6 functionality was explicitely disabled in the Github CI,
although it is not clear to me why that was the case,
since IPv6 was not used there but there is no good reason
to not compile the functionality at all.
This should fix some of the problems with #2115
> Do not explicitely disable IPv6 in the CI

- lib/utils_cmd.c
- lib/utils_cmd.h
The warning I got on gcc 15.1.1 (Arch) was:
```
check_apt.c: In function ‘run_upgrade’:
check_apt.c:319:50: warning: passing argument 1 of ‘cmd_file_read’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
319 |                 result.errorcode = cmd_file_read(input_filename, &chld_out, 0);
|                                                  ^~~~~~~~~~~~~~
In file included from runcmd.h:28,
from check_apt.c:38:
../lib/utils_cmd.h:23:19: note: expected ‘char *’ but argument is of type ‘const char *’
23 | int cmd_file_read(char *, output *, int);
|                   ^~~~~~
```
The man page of glibc states than `int open(const char *path, int oflag, ...);` is the
prottype. `cmd_file_read` uses open here `if ((fd = open(filename, O_RDONLY)) == -1) `
> changed filename in cmd_file_read to const char * (check_apt warning)

- configure.ac
- plugins/check_fping.c
If fping is used with a target that has dual stack v4/v6, then due to
the logic during command construction, ipv4 will never be checked as v6
is preferred by fping.
This explicitly flags -4/-6 when it is requested by the user.
> Improve handling of -4/-6

- configure.ac
- plugins/check_fping.c
- plugins/check_fping.d/config.h
This PR adds some command line options to `check_fping` which mirror some options which were
added to `fping` with version 5.2 and 5.3.
closes #2126
> Check fping 5.3 options

- plugins/check_http.c
Just running `clang-format` and add some suggestions from `clangd` + declaring all the variables `static`.
Makes me a little bit more happy although I am not going to invest more time in `check_http`.
> check_http: formatting + no-brainer linter fixes

- plugins/check_mysql.c
In the Debian Bug tracker (and then Github) a person pointed out, that a MySQL server does not respond with a hint that is indeed the MySQL software but only with the version string.
Which makes sense if one assumes to be the only implementation.
This commit changes the behaviour of the Replica check to assume that the counterpart is a MySQL server if there are no hints that it is a MariaDB server.
I was made aware of this in #2068 (set comments) (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1116027)
> check_mysql: Assume MySQL server by default (in replica check)

- plugins/check_users.c
- plugins/check_users.d/users.c
This fixes building check_users on OpenBSD (ref #2152)
> fixes check_users build on OpenBSD (without utmpx)

- plugins/check_mysql.c
Due to MySQL changing several term in Version 8.0.22 the way to determine the status of replicas has changed.
To adapt to these changes in a517dc614e44650a7e9204c4202feec7a40fd37f check_mysql was modified to adapt to different versions. Some parts were missed though which results in failures to detect the replica status properly.
This parts should be contained in this commit.
Should also fix some of the problems discussed in #2068
Ping @waja therefore. these changes have to added to the maintenance branch
> More renaming due to MySQL name chances

- plugins/check_snmp.c
> check_snmp: remove useless headers
